//***************************************************************************
//                          pvapp.h  -  description
//                             -------------------
//  begin            : dom. mai. 11 18:39:57 2025
//  generated by     : pvdevelop (C) Lehrig Software Engineering
//  email            : lehrig@t-online.de
//***************************************************************************
#ifndef _PVAPP_H_
#define _PVAPP_H_

#ifdef USE_INETD
static int trace=0; // todo: set trace=0 if you do not want printf() within event loop
#else
static int trace=1; // todo: set trace=0 if you do not want printf() within event loop
#endif

#include "processviewserver.h"
// todo: comment me out
#include "rlmodbusclient.h"
//#include "rlsiemenstcpclient.h"
//#include "rlppiclient.h"
#include "modbusdaemon.h"             // this is generated. Change for name.h -> "name.mkmodbus"
//#include "siemensdaemon.h"            // this is generated
//#include "ppidaemon.h"                // this is generated

int show_mask1(PARAM *p);


typedef struct{
short V1,V2,V3,
      I1,I2,I3,
      argV1,argV2,argV3,
      argI1,argI2,argI3,
      DO0, DO1, DI0, DI1,
      Timer0, Timer1, Status, Timer;
}CMT;

extern CMT v;

#include <stdlib.h> // Para strtod
#include <errno.h>  // Para ERANGE e outras macros de erro

int isValidDouble(const char *str, double *value);

#endif
